# Site settings
title: "Ziang Ye"
description: "AI & DataScience"
url: "https://whi497.github.io" # Your GitHub Pages domain
baseurl: "/leaf.github.io" # The repository/subdirectory name

# Author info
author:
  name: "Ziang Ye"
  email: "yza03@mail.ustc.edu.cn"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink style for blog posts
permalink: /writings/:year/:month/:day/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
